# https://cloud.google.com/appengine/docs/standard/python/config/appref
# "The recommended approach is to remove the application element from your app.yaml file and instead,
# use a command-line flag to specify your application ID:
#     gcloud app deploy --project [YOUR_PROJECT_ID]
# "
#
# "The recommended approach is to remove the version element from your app.yaml file and instead,
# use a command-line flag to specify your version ID:
#     gcloud app deploy -v [YOUR_VERSION_ID]
# "
# version: 1
runtime: python27
api_version: 1
threadsafe: true

# instances and scaling
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  #max_idle_instances: automatic  # default value
  max_idle_instances: 1
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

inbound_services:
- warmup

handlers:
  # profiler
- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: .*
  script: handler.app

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*~
- ^(.*/)?Icon\r
- ^static/src
