runtime: python27
api_version: 1
threadsafe: true
service: default

# instances and scaling
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  #max_idle_instances: automatic  # default value
  max_idle_instances: 1
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: markupsafe
  version: latest

inbound_services:
- warmup

handlers:
  # profiler
- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: .*
  script: atuin.handler.app

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*~
- ^(.*/)?Icon\r
- ^static/src
- ^.*\.po[t]
- ^.*requirements\.txt
